### PR TITLE
Added license note to bottom of README.md

### PR DESCRIPTION
**Pull request by jconniff**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by drewfish** [comment]
+1

**Comment by jconniff** [comment]
@drewfish Thanks for reviewing. Looks like "Only those with write access to this repository can merge pull requests." Which is not me.

**Comment by drewfish** [comment]
Heh, me neither. Perhaps one of the other people watching this repo can merge.

**Pull request merged**
